In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [3]:
train_df.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,...,100.0,50.0,0,0,577150,122018,32000,170200,N,N
1,141451,141451,21000,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,...,85.0,33.3,0,0,132750,27896,15900,35398,N,N
2,321143,321143,20000,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,...,85.7,33.3,0,0,628160,114043,22600,90340,N,N
3,11778,11778,3000,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,...,100.0,16.7,1,0,42006,20761,19900,15406,N,N
4,169382,169382,30000,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,...,100.0,66.7,0,0,283248,109056,79500,58778,N,N

In [4]:
test_df.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,67991,67991,40000,0.0819,814.70,MORTGAGE,140000.0,Not Verified,low_risk,n,...,97.7,0.0,0,0,527975,70914,74600,99475,N,N
1,25429,25429,6000,0.1524,208.70,RENT,55000.0,Not Verified,low_risk,n,...,66.7,0.0,0,0,34628,23460,5900,23628,N,N
2,38496,38496,3600,0.1695,128.27,RENT,42000.0,Not Verified,low_risk,n,...,100.0,0.0,0,0,23100,19183,7300,15000,N,N
3,19667,19667,20000,0.1524,478.33,RENT,100000.0,Not Verified,low_risk,n,...,100.0,50.0,0,0,56481,43817,13800,35981,N,N
4,37505,37505,3600,0.1240,120.27,RENT,50000.0,Not Verified,low_risk,n,...,100.0,25.0,0,0,45977,32448,21000,24977,N,N

In [5]:
# Convert categorical data to numeric and separate target feature for training data
train_X = train_df.drop(['loan_status', 'Unnamed: 0', 'index'], axis=1)
train_X_dummies = pd.get_dummies(train_X)

train_y = LabelEncoder().fit_transform(train_df['loan_status'])

train_X_dummies

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,13375,0.1797,483.34,223000.0,29.99,0,0,15,0,39728,...,0,1,0,1,1,0,1,0,1,0
1,21000,0.1308,478.68,123000.0,11.26,2,0,16,0,9585,...,0,1,0,1,1,0,1,0,1,0
2,20000,0.1240,448.95,197000.0,11.28,0,0,12,0,16708,...,0,1,0,1,1,0,1,0,1,0
3,3000,0.1240,100.22,45000.0,18.08,0,0,12,1,8809,...,0,1,0,1,1,0,1,0,1,0
4,30000,0.1612,1056.49,133000.0,27.77,0,2,13,0,65420,...,0,1,0,1,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,19975,0.2565,801.09,28000.0,28.42,0,0,15,0,9679,...,0,1,0,1,1,0,1,0,1,0
12176,15000,0.1774,540.34,50000.0,23.43,4,0,16,0,3193,...,1,1,0,1,1,0,1,0,1,0
12177,3600,0.1862,131.28,60000.0,28.80,0,1,14,0,11804,...,0,1,0,1,1,0,1,0,1,0
12178,15000,0.0881,475.68,62000.0,11.44,0,0,5,0,157,...,0,1,0,1,0,1,1,0,1,0
12179,15000,0.1774,540.34,54080.0,21.66,1,1,5,0,8349,...,0,1,1,0,1,0,1,0,1,0

In [6]:
# Convert categorical data to numeric and separate target feature for testing data
test_X = test_df.drop(['loan_status', 'Unnamed: 0', 'index'], axis = 1)
test_X_dummies = pd.get_dummies(test_X)

test_y = LabelEncoder().fit_transform(test_df['loan_status'])

test_X_dummies

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Source Verified,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,40000,0.0819,814.70,140000.0,19.75,0,1,18,0,9471,...,0,0,1,0,1,1,0,1,0,1
1,6000,0.1524,208.70,55000.0,11.52,2,0,8,0,1280,...,0,0,1,0,1,1,0,1,0,1
2,3600,0.1695,128.27,42000.0,6.74,0,0,6,0,4757,...,0,0,1,0,1,1,0,1,0,1
3,20000,0.1524,478.33,100000.0,12.13,0,2,7,0,12731,...,0,0,1,0,1,1,0,1,0,1
4,3600,0.1240,120.27,50000.0,16.08,0,3,6,0,10413,...,0,0,1,0,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,30000,0.1240,673.42,140480.0,15.74,0,0,20,0,23215,...,1,0,1,1,0,1,0,1,0,1
4698,24000,0.0756,747.22,50000.0,26.81,0,0,9,0,459,...,0,0,1,0,1,1,0,1,0,1
4699,10000,0.2305,387.36,33000.0,38.51,0,2,7,0,6342,...,0,1,1,1,0,1,0,1,0,1
4700,8000,0.1862,205.86,38000.0,16.36,0,1,8,1,11636,...,1,0,1,0,1,1,0,1,0,1
4701,30000,0.2055,1123.34,180000.0,12.06,0,0,8,0,4771,...,1,0,1,1,0,1,0,1,0,1

In [7]:
# add missing dummy variables to testing set - missing debt_settlement_flag_Y column in testing data
print(f"Train: {train_X_dummies.shape}, Test: {test_X_dummies.shape}")

test_X_dummies["debt_settlement_flag_Y"]=0
        
print(f"Train: {train_X_dummies.shape}, Test: {test_X_dummies.shape}")

Train: (12180, 92), Test: (4702, 91)
Train: (12180, 92), Test: (4702, 92)

### Model Prediction:
I predict that the Random Forest Classifier model will perform better than the Logistic Regression overall because the Random Forest works with smaller subsets of data to build a strong classifier, whereas the Logistic Regression uses the dataset as a whole for its predictions

In [8]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(train_X_dummies, train_y)
print(f"Training Data Score: {classifier.score(train_X_dummies, train_y)}")
print(f"Testing Data Score: {classifier.score(test_X_dummies, test_y)}")

Training Data Score: 0.6508210180623973
Testing Data Score: 0.5168013611229264

C:\Users\Cara\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [9]:
# Train a Random Forest Classifier model and print the model score
from sklearn.ensemble import RandomForestClassifier
RFclassifier = RandomForestClassifier(random_state=42).fit(train_X_dummies, train_y)
print(f'Training Score: {RFclassifier.score(train_X_dummies, train_y)}')
print(f'Testing Score: {RFclassifier.score(test_X_dummies, test_y)}')

Training Score: 1.0
Testing Score: 0.6401531263292216

In [10]:
# Scale the data
scaler = StandardScaler().fit(train_X_dummies)
train_X_scaled = scaler.transform(train_X_dummies)
test_X_scaled = scaler.transform(test_X_dummies)

### Scaled Model Prediction:
I expect that the Linear Regression model will improve with the scaled data, but I would still expect the Random Forest model to perform better, as scaling may allow it to find more accurate trees with the subsets of data.

In [11]:
# Train the Logistic Regression model on the scaled data and print the model score
classifier = LogisticRegression()
classifier.fit(train_X_scaled, train_y)
print(f"Training Data Score: {classifier.score(train_X_scaled, train_y)}")
print(f"Testing Data Score: {classifier.score(test_X_scaled, test_y)}")

Training Data Score: 0.7078817733990148
Testing Data Score: 0.767333049766057

C:\Users\Cara\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [12]:
# Train a Random Forest Classifier model on the scaled data and print the model score
RFclassifier = RandomForestClassifier(random_state=42).fit(train_X_scaled, train_y)
print(f'Training Score: {RFclassifier.score(train_X_scaled, train_y)}')
print(f'Testing Score: {RFclassifier.score(test_X_scaled, test_y)}')

Training Score: 1.0
Testing Score: 0.638664398128456

### Model Results:
The Random Forest model did better with the un-scaled data than the Logistic Regression model, but the Logistic Regression model with the scaled data did the best overall. The Random Forest model did about the same with both the scaled and unscaled data, which I found surprising.